-- SHOPPING D + ARGOPLAN
-- EXECUTE UMA ÚNICA VEZ NO SQL EDITOR DO SUPABASE.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.lojas (
  id bigint generated by default as identity primary key,
  andar text not null,
  luc text not null,
  nome text not null,
  criado_em timestamptz not null default now()
);

create table if not exists public.configuracoes (
  chave text primary key,
  valor text not null
);

create table if not exists public.admin_config (
  id integer primary key default 1 check (id=1),
  email text not null,
  senha_hash text not null
);

insert into public.configuracoes(chave,valor)
values ('vagas_estacionamento','551')
on conflict (chave) do nothing;

insert into public.admin_config(id,email,senha_hash)
values (1,'admin@shoppingd.com.br',extensions.crypt('argoplangabriel2026',extensions.gen_salt('bf')))
on conflict (id) do update
set email=excluded.email,
    senha_hash=excluded.senha_hash;

insert into public.lojas(andar,luc,nome)
select v.andar,v.luc,v.nome
from (values
('PISO TÉRREO','60','SAPATARIA DO FUTURO'),
('PISO 2','2321','VIVO'),
('PISO 2','2060','O BOTICÁRIO'),
('PISO TÉRREO','316 A','AMERICANAS'),
('PISO 1','QP1','STAR MAKE'),
('PISO TÉRREO','400/01','PÉ DO SUCO'),
('PISO TÉRREO','402','SIMTEC'),
('PISO 1','1050','MC DONALD''S'),
('PISO 1','1113','MONTEBELLO'),
('PISO 2','2056-A','AROMA CAFÉ'),
('PISO TÉRREO','30','PERNAMBUCANAS'),
('PISO 1','1055-A','CACAU SHOW'),
('PISO 1','1050 A','MAREMANNA'),
('PISO 2','2118','ZEN ZEN'),
('PISO 1','1031','PONTAL'),
('PISO 2','2117','NATURA'),
('PISO 1','1055','PODEROSO TIMÃO'),
('PISO 1','1056','CHILLI BEANS'),
('PISO 1','1000','CAEDU'),
('PISO 1','1053-A','GRÃO EXPRESSO'),
('PISO 1','10','CINEMARK'),
('PISO 1','1049','DIVINO FOGÃO'),
('PISO 1','1200/08','CRUZEIROS BAR'),
('PISO 1','1315','KING SNEAKERS'),
('PISO 1','1225/6','LE POSTICHE'),
('PISO 2','Q203','TIM'),
('PISO 1','1053','FELIZ FARMA'),
('PISO 2','2104/09','EMPÓRIO ALEX'),
('PISO TÉRREO','315','KIDSTOCK'),
('PISO 1','Q102','NIKIDS DOCES'),
('PISO 1','1060','ELI RIBEIRO'),
('PISO 1','1222','BANNER BRASIL'),
('PISO 1','1045','ESPETÃO RESTAURANTE LTDA.'),
('PISO 2','2067','EVENSEN PHOTOGRAPHY'),
('PISO TÉRREO','403','FMW'),
('PISO 1','1223','SHOPBLACK'),
('PISO TÉRREO','Q002','LETRINHA'),
('PISO 1','1057','CLARO'),
('PISO 1','1318/19','STAR CÂMBIO'),
('PISO 1','1047/48','GIRAFFAS'),
('PISO 2','2116','ATLET'),
('PISO TÉRREO','Q014','GÊMEOS ANIME'),
('PISO 2','2119','H-CASES'),
('PISO 1','1116','HERA MODAS'),
('PISO TÉRREO','Q103','IN LOVE STORE'),
('PISO TÉRREO','Q101','DUELO POKEMON'),
('PISO TÉRREO','58','KIKA BIJU'),
('PISO 1','1301 A','LINA GOLD'),
('PISO 1','1033/35','NAMIB'),
('PISO 1','1013/16','JOHNNY ROCKETS'),
('PISO 1','1119','LUPO'),
('PISO 1','1117','KIARA D''SOLE'),
('PISO 2','2318','CASA DA SAPATILHA'),
('PISO 1','1053','PLANET CHICKEN'),
('G1','QG1-02','LOCALIZA'),
('PISO TÉRREO','415','LOTÉRICA'),
('PISO 2','2222','MORANA'),
('PISO 1','1059','MADRINHAS E CONVIDADAS'),
('PISO 1','1030','T-REX JUMP'),
('PISO TÉRREO','QT012','T-REX ADVENTURE'),
('PISO TÉRREO','Q035/0408','T-REX GAMES'),
('ÁREA EXTERNA','QG5-02','T-REX PARK'),
('PISO TÉRREO','1','T-REX POOL'),
('PISO 2','2049','MANIA DE CHURRASCO'),
('PISO 2','2306','CÓDIGO GIRLS'),
('PISO 1','QP1','QUIOSQUE DO CELULAR'),
('PISO TÉRREO','311/12','MANU BABY'),
('PISO 1','1115','SLIPPER'),
('PISO 1','1320/1','MARÍLIA MARQUES'),
('PISO 1','1103/04','MANSÃO DAS NOIVAS'),
('PISO 2','2046','SPOLETTO'),
('PISO 2','2052/53','MEI MEI'),
('PISO 2','Q201','YOGGI'),
('PISO TÉRREO','Q006','FINI'),
('PISO 2','2316/17','WORLD TENNIS'),
('PISO 2','2058 A','PAPPU''S'),
('PISO TÉRREO','315','PASTEL DO REGINA'),
('PISO 2','2218/19','POUPATEMPO'),
('PISO 2','2045','VIVENDA DO CAMARÃO'),
('PISO 1','1304/14','PREÇOLÂNDIA'),
('PISO TÉRREO','59','PRINT GO'),
('PISO 2','2037/38','43 GRAUS'),
('PISO 1','1111','RENATA STYLE'),
('PISO 2','2016','RENNER'),
('PISO TÉRREO','309 A','REI DO MATE'),
('PISO 2','2319','NOVISSA'),
('PISO 2','Q-2027','ART CHURROS'),
('PISO 1','1052','GRILETTO'),
('PISO TÉRREO','061/62/63','SANTA MADRE PIZZARIA'),
('PISO 2','2000','INOVA ACADEMIA'),
('PISO 2','2220','STOP DESPACHANTE'),
('PISO 1','1300','ÓTICA 2001'),
('PISO 1','1107/1118','AMIGA MODAS'),
('PISO 2','2066','SUPER CHIC'),
('PISO 2','2008/09','TEAM ONE'),
('PISO 1','1316/17','TENNIS ONE'),
('PISO 1','Q114','TOUTTI'),
('PISO 1','2224','VESTI PIJAMAS'),
('PISO TÉRREO','50 A','POLO WEAR'),
('PISO TÉRREO','314','CHIQUINHO SORVETES'),
('PISO TÉRREO','QPT','MR. PRETZELS'),
('PISO 2','2061','MINISO'),
('PISO 2','2312','BURGER KING'),
('PISO 2','2054/55','POPEYES')
) as v(andar,luc,nome)
where not exists (select 1 from public.lojas);

alter table public.lojas enable row level security;
alter table public.configuracoes enable row level security;
alter table public.admin_config enable row level security;

drop policy if exists "public_select_lojas" on public.lojas;
create policy "public_select_lojas"
on public.lojas for select to anon, authenticated using (true);

drop policy if exists "public_select_config" on public.configuracoes;
create policy "public_select_config"
on public.configuracoes for select to anon, authenticated using (true);

revoke all on public.admin_config from anon, authenticated;
grant select on public.lojas to anon, authenticated;
grant select on public.configuracoes to anon, authenticated;

create or replace function public.validar_admin(p_email text,p_senha text)
returns boolean
language sql
security definer
set search_path=public
as $$
select exists(
  select 1 from public.admin_config
  where lower(email)=lower(p_email)
    and senha_hash=extensions.crypt(p_senha,senha_hash)
);
$$;

create or replace function public.admin_adicionar_loja(
 p_email text,p_senha text,p_andar text,p_luc text,p_nome text
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare novo_id bigint;
begin
 if not public.validar_admin(p_email,p_senha) then
  raise exception 'Login administrativo inválido';
 end if;
 insert into public.lojas(andar,luc,nome)
 values(trim(p_andar),trim(p_luc),trim(p_nome))
 returning id into novo_id;
 return novo_id;
end;
$$;

create or replace function public.admin_excluir_loja(
 p_email text,p_senha text,p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
 if not public.validar_admin(p_email,p_senha) then
  raise exception 'Login administrativo inválido';
 end if;
 delete from public.lojas where id=p_id;
 return true;
end;
$$;

create or replace function public.admin_alterar_vagas(
 p_email text,p_senha text,p_vagas integer
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
 if not public.validar_admin(p_email,p_senha) then
  raise exception 'Login administrativo inválido';
 end if;
 if p_vagas < 0 then raise exception 'Quantidade inválida'; end if;
 insert into public.configuracoes(chave,valor)
 values('vagas_estacionamento',p_vagas::text)
 on conflict(chave) do update set valor=excluded.valor;
 return true;
end;
$$;

grant execute on function public.validar_admin(text,text) to anon, authenticated;
grant execute on function public.admin_adicionar_loja(text,text,text,text,text) to anon, authenticated;
grant execute on function public.admin_excluir_loja(text,text,bigint) to anon, authenticated;
grant execute on function public.admin_alterar_vagas(text,text,integer) to anon, authenticated;
